# Generated by Django 4.2.1 on 2023-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_estd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='estd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
