# Generated by Django 4.2.1 on 2023-07-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('UI/UX', 'UI/UX'), ('Human Resource', 'Human Resource'), ('Operations', 'Operations')], max_length=100, null=True)),
                ('upload_resume', models.FileField(blank=True, null=True, upload_to='uploaded_resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
