# Generated by Django 4.1.7 on 2023-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Developer", "Developer"),
                    ("Consultant", "Consultant"),
                    ("Analyst", "Analyst"),
                    ("Manager", "Manager"),
                    ("UI/UX", "UI/UX"),
                    ("Human Resource", "Human Resource"),
                    ("Operations", "Operations"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
