# Generated by Django 4.2.1 on 2023-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
