# Generated by Django 3.2.7 on 2023-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Sports', 'Sports'), ('Energy', 'Energy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Gujarat', 'Gujarat'), ('Kashmir', 'Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
